[package]
name = "geniusclip-engine"
description = "Screen capture, hardware encoding and replay buffer engine for GeniusClip"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
ffmpeg-sys-next.workspace = true
windows.workspace = true

[dev-dependencies]
serde_json.workspace = true
env_logger = "0.11"
